name: Node.js Code Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: Scan Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify your Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Run linters and tests
        run: |
          npm run lint   # Ensure you have a lint script in package.json
          npm test       # Ensure you have a test script in package.json
